### ISSUE TITLE
Create token relationship for requests/responses

### ISSUE THREAD

**Issue by cantino** [cantino/feedadoc#2]
The link should have a long GUID in it for authentication.

The page should allow editing of their info and Request.

**Comment by tuntisz** [comment]
I'll claim this one :beers:

**Comment by cantino** [comment]
Sounds great.

**Comment by tuntisz** [comment]
Accidentally unassigned when trying to mark as in-progress. Anyhow, I have a PR coming soon

**Comment by tuntisz** [comment]
[This PR](https://github.com/cantino/feedadoc/pull/10) gets us most of the way there. However, I'd like to break this down into more tickets. Assuming that work makes it in, this would open the door for a couple tickets:
1. Email providers the token on creation
2. Creating routes and views to handle CRUD operations
3. Create mutations to allow CRUD operations

**Comment by cantino** [comment]
Go ahead and make tickets as you see fit.
